module.exports = {
  "Envelope":{
    "id":"Envelope",
    "properties":{
      "response":[
        "Domain",
        "Movie",
        "List[Domain]",
        "List[Movie]",
      ],
      "responseTime":"integer",
      "name":{
        "type":"string"
      }
    }
  },
  "Count":{
    "id":"Count",
    "properties": {
      "count":{
        "type":"integer"
      }
    }
  },
  "Movie":{
    "id":"Movie",
    "properties":{
      "id":{
        "type":"integer"
      },
      "title":{
        "type":"string"
      },
      "released":{
        "type":"integer"
      },
      "tagline":{
        "type":"string"
      }
    }
  },
  "Domain":{
    "id":"Domain",
    // "required": ["id"],
    "properties":{
      "id":{
        "type":"string"
      },
      "name":{
        "type":"string"
      }
    }
  }
};