// module.exports = {
//   "Envelope":{
//     "id":"Envelope",
//     "properties":{
//       "response":[
//         "Domain",
//         "Gist",
//         "List[Domain]",
//         "List[Gist]",
//       ],
//       "responseTime":"integer",
//       "name":{
//         "type":"string"
//       }
//     }
//   },
//   "Count":{
//     "id":"Count",
//     "properties": {
//       "count":{
//         "type":"integer"
//       }
//     }
//   },
//   "Gist":{
//     "id":"Gist",
//     "properties":{
//       "id":{
//         "type":"integer"
//       },
//       "title":{
//         "type":"string"
//       },
//       "released":{
//         "type":"integer"
//       },
//       "tagline":{
//         "type":"string"
//       }
//     }
//   },
//   "Domain":{
//     "id":"Domain",
//     // "required": ["id"],
//     "properties":{
//       "id":{
//         "type":"string"
//       },
//       "name":{
//         "type":"string"
//       }
//     }
//   }
// };